import { PropertyRecord } from "../types";

export const sampleRecords: PropertyRecord[] = [
  {
    owner_name: "John Miller",
    property_address: "1420 Brookmere Way",
    property_city: "Cumming",
    property_state: "GA",
    property_zip: "30041",
    county: "Forsyth County",
    latitude: "34.2073",
    longitude: "-84.1402",
    property_type: "Single Family Residential",
    year_built: "1982",
    market_value: "475000",
    last_sale_date: "2012-04-12",
    mailing_address: "87 Harbor Drive",
    mailing_city: "Tampa",
    mailing_state: "FL",
    phone: "404-555-0148",
    email: "john@example.com",
    owner_property_count: "1",
    active_mortgage: "No",
    tax_status: "Current",
    homestead_exemption: "No",
    vacancy_flag: "No",
    estimated_ltv: "0.35",
    mortgage_recording_date: "2012-04-12",
    school_rating: "8.4",
    bedrooms: "4",
    last_permit_date: "2004",
    property_condition: "Dated original finishes",
  },
  {
    owner_name: "Lydia Ross",
    property_address: "91 Cedar Trace",
    property_city: "Roswell",
    property_state: "GA",
    property_zip: "30075",
    county: "Fulton County",
    latitude: "34.0395",
    longitude: "-84.3601",
    property_type: "Residential",
    year_built: "1974",
    market_value: "825000",
    last_sale_date: "2009-10-19",
    mailing_address: "201 W 72nd St",
    mailing_city: "New York",
    mailing_state: "NY",
    owner_property_count: "3",
    active_mortgage: "No",
    tax_status: "Unpaid",
    tax_due: "3400",
    homestead_exemption: "No",
    vacancy_flag: "Yes",
    estimated_ltv: "0.25",
    mortgage_recording_date: "2009-10-19",
    school_rating: "9.1",
    bedrooms: "4",
    last_transfer_type: "Warranty deed",
    property_condition: "Needs cosmetic updates",
  },
  {
    owner_name: "Peachtree Rentals LLC",
    property_address: "340 Pinebend Road",
    property_city: "Alpharetta",
    property_state: "GA",
    property_zip: "30009",
    county: "Fulton County",
    latitude: "34.0754",
    longitude: "-84.2941",
    property_type: "Multi-Family 2-4 Units",
    year_built: "1988",
    market_value: "612000",
    last_sale_date: "2008-03-03",
    mailing_address: "PO Box 44",
    mailing_city: "Birmingham",
    mailing_state: "AL",
    owner_property_count: "8",
    active_mortgage: "Unknown",
    tax_status: "Current",
    homestead_exemption: "No",
    estimated_ltv: "0.55",
    mortgage_recording_date: "2008-03-03",
    school_rating: "7.6",
    bedrooms: "3",
    property_condition: "Fair rental condition",
  },
  {
    owner_name: "Marsha Green",
    property_address: "7 Post Oak Lane",
    property_city: "Johns Creek",
    property_state: "GA",
    property_zip: "30022",
    county: "Fulton County",
    latitude: "34.0289",
    longitude: "-84.1986",
    property_type: "Single Family",
    year_built: "2001",
    market_value: "540000",
    last_sale_date: "2014-08-09",
    mailing_address: "7 Post Oak Lane",
    mailing_city: "Johns Creek",
    mailing_state: "GA",
    owner_property_count: "1",
    active_mortgage: "Yes",
    tax_status: "Current",
    homestead_exemption: "Yes",
    school_rating: "8.7",
    bedrooms: "4",
    property_condition: "Good",
  },
  {
    owner_name: "Estate of Henry Cole",
    property_address: "5225 Valley Stream",
    property_city: "Cumming",
    property_state: "GA",
    property_zip: "30040",
    county: "Forsyth County",
    latitude: "34.1858",
    longitude: "-84.1397",
    property_type: "Residential Land",
    year_built: "1970",
    market_value: "275000",
    last_sale_date: "",
    mailing_address: "49 Clubhouse Court",
    mailing_city: "Asheville",
    mailing_state: "NC",
    owner_property_count: "2",
    active_mortgage: "No",
    tax_status: "Current",
    homestead_exemption: "No",
    senior_exemption: "Yes",
    last_transfer_type: "Probate estate transfer",
    school_rating: "7.2",
    bedrooms: "0",
  },
  {
    owner_name: "Diane Wallace",
    property_address: "2190 Meadowglenn Trail",
    property_city: "Milton",
    property_state: "GA",
    property_zip: "30004",
    county: "Fulton County",
    latitude: "34.1322",
    longitude: "-84.3007",
    property_type: "Single Family Residential",
    year_built: "2004",
    market_value: "1650000",
    last_sale_date: "2005-05-14",
    mailing_address: "2190 Meadowglenn Trail",
    mailing_city: "Milton",
    mailing_state: "GA",
    owner_property_count: "1",
    active_mortgage: "Yes",
    tax_status: "Current",
    homestead_exemption: "Yes",
    senior_exemption: "Yes",
    estimated_ltv: "0.30",
    mortgage_recording_date: "2005-05-14",
    school_rating: "9.6",
    bedrooms: "5",
  },
  {
    owner_name: "Nina Park",
    property_address: "44 Riverstone Walk",
    property_city: "Roswell",
    property_state: "GA",
    property_zip: "30076",
    county: "Fulton County",
    latitude: "34.0232",
    longitude: "-84.3616",
    property_type: "Townhome",
    year_built: "2016",
    market_value: "410000",
    last_sale_date: "2022-07-21",
    mailing_address: "44 Riverstone Walk",
    mailing_city: "Roswell",
    mailing_state: "GA",
    owner_property_count: "1",
    active_mortgage: "Yes",
    tax_status: "Current",
    homestead_exemption: "Yes",
    school_rating: "6.4",
    bedrooms: "3",
  },
  {
    owner_name: "North Point Storage Partners LLC",
    property_address: "7600 North Point Parkway",
    property_city: "Alpharetta",
    property_state: "GA",
    property_zip: "30005",
    county: "Fulton County",
    latitude: "34.0554",
    longitude: "-84.2812",
    property_type: "Commercial self storage",
    year_built: "1992",
    market_value: "2400000",
    last_sale_date: "2018-11-02",
    mailing_address: "1200 Main Street",
    mailing_city: "Atlanta",
    mailing_state: "GA",
    owner_property_count: "120",
    active_mortgage: "Yes",
    tax_status: "Current",
    estimated_ltv: "0.70",
  },
  {
    owner_name: "Pranav Patel",
    property_address: "88 Golden Lake Drive",
    property_city: "Lawrenceville",
    property_state: "GA",
    property_zip: "30043",
    county: "Gwinnett County",
    latitude: "33.9562",
    longitude: "-83.9879",
    property_type: "Single Family Residential",
    year_built: "1989",
    market_value: "430000",
    last_sale_date: "2006-06-06",
    mailing_address: "410 Laurel Street",
    mailing_city: "Charlotte",
    mailing_state: "NC",
    owner_property_count: "1",
    active_mortgage: "No",
    tax_status: "Current",
    estimated_ltv: "0.20",
    school_rating: "6.8",
    bedrooms: "4",
  },
];

export const csvTemplateHeaders = [
  "owner_name",
  "property_address",
  "property_city",
  "property_state",
  "property_zip",
  "county",
  "latitude",
  "longitude",
  "property_type",
  "year_built",
  "market_value",
  "assessed_value",
  "last_sale_date",
  "mailing_address",
  "mailing_city",
  "mailing_state",
  "phone",
  "email",
  "owner_property_count",
  "active_mortgage",
  "tax_status",
  "tax_due",
  "homestead_exemption",
  "senior_exemption",
  "vacancy_flag",
  "estimated_ltv",
  "estimated_equity",
  "equity_percent",
  "mortgage_recording_date",
  "mortgage_age_years",
  "last_transfer_type",
  "foreclosure_status",
  "school_rating",
  "school_premium",
  "bedrooms",
  "last_permit_date",
  "property_condition",
  "assigned_elementary_school",
  "assigned_middle_school",
  "assigned_high_school",
  "school_performance_score",
  "school_premium_score",
  "census_median_income",
  "census_median_home_value",
  "census_owner_occupancy_rate",
  "census_age_65_plus_rate",
  "census_vacancy_rate",
  "fred_mortgage30_rate",
  "fred_atlanta_unemployment_rate",
  "fred_county_hpi_growth",
  "osm_amenity_score",
  "osm_park_count_1mi",
  "osm_grocery_count_1mi",
  "osm_major_road_nearby",
];
