import { PropertyRecord } from "../types";

export const sampleRecords: PropertyRecord[] = [
  {
    owner_name: "John Miller",
    property_address: "1420 Brookmere Way",
    property_city: "Cumming",
    property_state: "GA",
    county: "Forsyth County",
    property_type: "Single Family Residential",
    year_built: "1982",
    market_value: "475000",
    last_sale_date: "2012-04-12",
    mailing_address: "87 Harbor Drive",
    mailing_city: "Tampa",
    mailing_state: "FL",
    phone: "404-555-0148",
    email: "john@example.com",
    owner_property_count: "1",
    active_mortgage: "No",
    tax_status: "Current",
  },
  {
    owner_name: "Lydia Ross",
    property_address: "91 Cedar Trace",
    property_city: "Roswell",
    property_state: "GA",
    county: "Fulton County",
    property_type: "Residential",
    year_built: "1974",
    market_value: "825000",
    last_sale_date: "2009-10-19",
    mailing_address: "201 W 72nd St",
    mailing_city: "New York",
    mailing_state: "NY",
    owner_property_count: "3",
    active_mortgage: "No",
    tax_status: "Unpaid",
  },
  {
    owner_name: "Peachtree Rentals LLC",
    property_address: "340 Pinebend Road",
    property_city: "Alpharetta",
    property_state: "GA",
    county: "Fulton County",
    property_type: "Multi-Family 2-4 Units",
    year_built: "1988",
    market_value: "612000",
    last_sale_date: "2008-03-03",
    mailing_address: "PO Box 44",
    mailing_city: "Birmingham",
    mailing_state: "AL",
    owner_property_count: "8",
    active_mortgage: "Unknown",
    tax_status: "Current",
  },
  {
    owner_name: "Marsha Green",
    property_address: "7 Post Oak Lane",
    property_city: "Johns Creek",
    property_state: "GA",
    county: "Fulton County",
    property_type: "Single Family",
    year_built: "2001",
    market_value: "540000",
    last_sale_date: "2010-08-09",
    mailing_address: "7 Post Oak Lane",
    mailing_city: "Johns Creek",
    mailing_state: "GA",
    owner_property_count: "1",
    active_mortgage: "Yes",
    tax_status: "Current",
  },
  {
    owner_name: "Estate of Henry Cole",
    property_address: "5225 Valley Stream",
    property_city: "Cumming",
    property_state: "GA",
    county: "Forsyth County",
    property_type: "Residential Land",
    year_built: "1970",
    market_value: "275000",
    last_sale_date: "",
    mailing_address: "49 Clubhouse Court",
    mailing_city: "Asheville",
    mailing_state: "NC",
    owner_property_count: "2",
    active_mortgage: "No",
    tax_status: "Current",
  },
  {
    owner_name: "Pranav Patel",
    property_address: "88 Golden Lake Drive",
    property_city: "Lawrenceville",
    property_state: "GA",
    county: "Gwinnett County",
    property_type: "Single Family Residential",
    year_built: "1989",
    market_value: "430000",
    last_sale_date: "2006-06-06",
    mailing_address: "410 Laurel Street",
    mailing_city: "Charlotte",
    mailing_state: "NC",
    owner_property_count: "1",
    active_mortgage: "No",
    tax_status: "Current",
  },
];

export const csvTemplateHeaders = [
  "owner_name",
  "property_address",
  "property_city",
  "property_state",
  "county",
  "property_type",
  "year_built",
  "market_value",
  "last_sale_date",
  "mailing_address",
  "mailing_city",
  "mailing_state",
  "phone",
  "email",
  "owner_property_count",
  "active_mortgage",
  "tax_status",
];
